import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { MarchyBar } from '../backend/server.mjs';

test('real daemon protocol: preview, CRUD, app layouts, privacy, export, rollback and shutdown', async t => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'marchybar-protocol-'));
  const app = await new MarchyBar({socketPath:path.join(tmp,'run/control.sock'),configDir:path.join(tmp,'config'),stateDir:path.join(tmp,'state'),previewOnly:true,live:false}).start();
  t.after(async()=>{await app.stop();fs.rmSync(tmp,{recursive:true,force:true})});
  const socket = net.createConnection(app.socketPath);
  await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('error',reject)});
  t.after(()=>socket.destroy());
  let next=0, buffer='';const pending=new Map();
  socket.on('data',chunk=>{buffer+=chunk;let i;while((i=buffer.indexOf('\n'))>=0){const m=JSON.parse(buffer.slice(0,i));buffer=buffer.slice(i+1);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id)}}});
  const request=(method,params={},revision=app.store.revision)=>new Promise(resolve=>{const id=++next;pending.set(id,resolve);socket.write(JSON.stringify({id,method,params,revision})+'\n')});
  const ok=async(...args)=>{const r=await request(...args);assert.equal(r.ok,true,r.error);return r.data};
  assert.equal((await request('hello',{protocolVersion:2})).ok,false);
  assert.equal((await ok('hello',{protocolVersion:1})).presets.length,6);
  assert.equal(fs.statSync(app.socketPath).mode&0o777,0o600);
  const p=await ok('preset.create',{name:'Integration',from:'everyday'});
  p.pages[0].widgets[0].label='My spaces';
  await ok('preset.save',{preset:p});
  assert.equal((await request('preset.save',{preset:p},'stale')).ok,false);
  const frame=await ok('preview',{preset:p,width:2008});assert.equal(frame.geometry.width,2008);assert.ok(frame.boxes[0].w>0);
  await new Promise(r=>setTimeout(r,150));
  assert.equal(fs.readFileSync(app.previewPath).subarray(1,4).toString(),'PNG');
  await ok('preset.apply',{id:p.id});assert.equal(app.active.id,p.id);
  await ok('automatic');await ok('simulate',{data:{app:'chromium',title:'Private page'}});assert.equal(app.active.id,'browser');
  await ok('try',{preset:p});assert.equal(app.active.id,p.id);assert.ok(app.trial.ends>Date.now());
  await ok('revert');assert.equal(app.active.id,'browser');
  const classic=app.store.get('classic');classic.pages[0].widgets[0].label='SECRET';await ok('preset.save',{preset:classic});
  await ok('simulate',{locked:true});assert.equal(app.active.id,'classic');assert.equal(app.active.preset.pages[0].widgets[0].label,'F1');assert.equal(app.snapshot().data.title,'');
  await ok('simulate',{locked:false});
  const tooWide=structuredClone(p);tooWide.pages[0].widgets=Array.from({length:24},(_,i)=>({id:'m'+i,type:'media',weight:1}));
  assert.equal((await request('preset.save',{preset:tooWide})).ok,false);
  const file=path.join(tmp,'export.json');await ok('file.export',{id:p.id,path:file});
  const imported=await ok('file.import',{path:file});assert.notEqual(imported.id,p.id);
  await ok('preset.delete',{id:imported.id,replacement:'everyday'});
  await ok('settings.save',{settings:{brightness:0}});
  assert.equal((await ok('get')).data.touchbar,0);
  await app.setBrightness(0);assert.equal(app.store.settings.brightness,0);
  assert.equal((await request('settings.save',{settings:{brightness:-1}})).ok,false);
  assert.equal((await request('settings.save',{settings:{brightness:256}})).ok,false);
  assert.equal((await request('hardware.enable')).ok,false);
  assert.equal((await request('not-a-method')).ok,false);
  await ok('preview.close');
});
